---

- name: Ensure keys folder exists locally
  file: path=keys state=directory
  connection: local
  run_once: true
  become: no

- name: Create randd user
  user: name=randd home=/home/randd shell=/bin/bash

- name: Copy binary
  copy:
    src: "{{BINARY}}"
    dest: /usr/bin
    mode: 0755

- name: Copy service file
  copy: src=randd.service dest=/etc/systemd/system/randd.service mode=0755
  notify: reload systemd

- name: Get node ID
  command: "cat /etc/nodeid"
  changed_when: false
  register: nodeid

- name: Make node infomation
  command: "echo node{{nodeid.stdout}}@{{inventory_hostname}}"
  register: nodeinfo

- name: Create remote testnet configurations
  command: "{{BINARY}} testnet --output-dir={{playbook_dir}}/testnets/{{TESTNET_NAME}} --chain-id={{TESTNET_NAME}}"
  responses:
        "Password for account 'node101' \(default misskiwi\):": ""
        "Password for account 'node102' \(default misskiwi\):": ""
        "Password for account 'node103' \(default misskiwi\):": ""
        "Password for account 'node104' \(default misskiwi\):": ""
  connection: local
  become: no
  run_once: false
  args:
    creates: "{{playbook_dir}}/testnets/{{TESTNET_NAME}}"

- name: Copy testnet node configurations
  copy:
    src: "{{playbook_dir}}/testnets/{{TESTNET_NAME}}/node{{nodeid.stdout_lines[0]}}/randd/config"
    dest: "/home/randd/.randd"
    mode: 0755
    owner: randd
    group: randd
    directory_mode: yes
    force: yes

- name: Copy testnet node data
  copy:
    src: "{{playbook_dir}}/testnets/{{TESTNET_NAME}}/node{{nodeid.stdout_lines[0]}}/randd/data"
    dest: "/home/randd/.randd"
    mode: 0755
    owner: randd
    group: randd
    directory_mode: yes
    force: yes

- name: fix permissions
  file:
    path: "/home/randd/.randd"
    owner: randd
    group: randd
    mode: 0755
    recurse: yes

    #- name: Update genesis.json to add faucet address
    #  command: "/usr/bin/randd add-genesis-account {{FAUCET_ADDRESS}} {{FAUCET_COINS}}"
    #  become: yes
    #  become_user: randd