---

- name: Copy binary
  copy:
    src: "{{RANDCLI_BINARY}}"
    dest: /usr/bin/randcli
    mode: 0755
  notify: restart randcli

- name: Copy service
  template:
    src: randcli.service.j2
    dest: /etc/systemd/system/randcli.service
  notify: systemctl

