---

- name: Stop service
  service: name=randd state=stopped

- name: Delete files
  file: "path={{item}} state=absent"
  with_items:
  - /usr/bin/randd
  - /home/randd/.randd
  - /home/randd/.randcli

