---

- name: Fetch genesis.json
  fetch: "src=/home/randd/.randd/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: randd

- name: Fetch config.toml
  fetch: "src=/home/randd/.randd/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: randd

